### ISSUE TITLE
BackwardThroughTime Error

### ISSUE THREAD

**Issue by robotsorcerer** [rracinskij/rnntest01#2]
Hi, 

Thanks for this example so freely provided.

What does the function `backwardThroughTime` do? Is it a valid torch backward propagation method?

For example, I tried running the `rnntest01.lua` example but I ran into the following error arising from line 56:

``` bash
   Step:    1    Input:     0.1  Target:    0.2  Output:    -0.054968322135166   Error:     0.065008845292422   
Step:   2    Input:     0.2  Target:    0.3  Output:    -0.05436093452622    Error:     0.1255716719183 
Step:   3    Input:     0.3  Target:    0.4  Output:    -0.04116540523981    Error:     0.19462691478041    
/home/lex/torch/install/bin/lua: rnntest01.lua:56: attempt to call method 'backwardThroughTime' (a nil value)
stack traceback:
    rnntest01.lua:56: in main chunk
    [C]: in function 'dofile'
    .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: ?

```

Would appreciate your reply.

**Comment by rracinskij** [comment]
Hi,
backwardThroughTime is a deprecated function, it was dropped from the Torch-rnn recently and I haven't updated my example yet. I suggest you to use following examples:

https://github.com/Element-Research/rnn/blob/master/examples/simple-sequencer-network.lua
https://github.com/Element-Research/rnn/blob/master/examples/recurrent-time-series.lua

Following discussion might be also useful to you:
https://github.com/Element-Research/rnn/issues/113

**Comment by robotsorcerer** [comment]
Thanks, that helps!
